device_: cuda
embed_dim: 1024
hyperparameters:
  dropout_attention: 0.3
  dropout_linear: 0.45
  learning_rate: 0.005
  optimizer: sgd
  weight_decay: 0.075
max_seq_length: 30
mhc_embed_len: 79
traJ_embed_len: 112
traV_embed_len: 118
trbJ_embed_len: 29
trbV_embed_len: 132
