device_: cuda
embed_dim: 1024
hyperparameters:
  dropout_attention: 0.3
  dropout_linear: 0.45
  learning_rate: 0.005
  optimizer: sgd
  weight_decay: 0.075
max_seq_length: 43
mhc_embed_len: 7
trbJ_embed_len: 17
trbV_embed_len: 68
